[package]
name = "rbaduk"
version = "0.1.0"
edition = "2021"

[dependencies]
engine = { path = "./crates/rbaduk-engine" }
mcts = { path = "./crates/rbaduk-mcts" }

[workspace]
members = [ 
    "crates/rbaduk-mcts",
    "crates/rbaduk-engine"
]
